on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
  
    - name: Install Pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0

    - name: Run Pylint
      run: pip install -r requirements.txt ; pylint **/*.py
    
    - name: Deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api-chessapp.server.ultras-playroom.xyz/update'
        method: 'PATCH'
        customHeaders: '{"X-Admin-Key": "***REMOVED***"}'