jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    
    - name: Install Pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0

    - name: Run Pylint
      run: pip install -r requirements.txt ; pylint **/*.py
    
    - name: Deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api-chessapp.server.ultras-playroom.xyz/update'
        method: 'PATCH'
        customHeaders: '{"X-Admin-Key": "***REMOVED***"}'