name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    
    - name: Deploy
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api-chessapp.server.ultras-playroom.xyz/update'
        method: 'PATCH'
        customHeaders: '{"X-Admin-Key": "***REMOVED***"}'